/*
  C source for GNU CHESS

  Revision: 1990-09-30

  Modified by Daryl Baker for use in MS WINDOWS environment

  This file is part of CHESS.

  CHESS is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY.  No author or distributor accepts responsibility to anyone for
  the consequences of using it or for whether it serves any particular
  purpose or works at all, unless he says so in writing.  Refer to the CHESS
  General Public License for full details.

  Everyone is granted permission to copy, modify and redistribute CHESS, but
  only under the conditions described in the CHESS General Public License.
  A copy of this license is supposed to have been given to you along with
  CHESS so you can know your rights and responsibilities.  It should be in a
  file named COPYING.  Among other things, the copyright notice and this
  notice must be preserved on all copies.
*/

#define TMDLG_MIN 300
#define TMDLG_MOV 100

#define TMDLG_600MIN  (TMDLG_MIN+600)
#define TMDLG_60MIN  (TMDLG_MIN+60)
#define TMDLG_30MIN  (TMDLG_MIN+30)
#define TMDLG_15MIN  (TMDLG_MIN+15)
#define TMDLG_5MIN   (TMDLG_MIN+5)

#define TMDLG_60MOV  (TMDLG_MOV+60)
#define TMDLG_40MOV  (TMDLG_MOV+40)
#define TMDLG_20MOV  (TMDLG_MOV+20)
#define TMDLG_10MOV  (TMDLG_MOV+10)
#define TMDLG_1MOV   (TMDLG_MOV+1)


